newrelic/opensource-website

- gatsby-config.js
- package-lock.json
- package.json
Adding segment to support internal google analytics session alignment
> feat: adding segment

- src/data/projects/newrelic-video-videojs-js.json
> fix: typo primaryLanguage => JavaScript

- src/data/projects/newrelic-video-theplatform-js.json
> fix: typo in primary language => JavaScript

- package-lock.json
- package.json
- src/components/GlobalHeader.js
- src/pages/home-page.module.scss
Includes fix for setting `Open Source` link in the header.
> chore(release): updating production to v1.0.5

- package-lock.json
- package.json
A typo that I didn't notice was breaking responsiveness on the homepage below 480px;
> fix(homepage): responsiveness bug

- package-lock.json
- package.json
- src/data/project-stats/newrelic-aws-log-ingestion.json
- src/data/project-stats/newrelic-newrelic-graphql-java-core.json
- src/data/project-stats/newrelic-nr1-slo-r.json
- src/data/project-stats/newrelic-opensource-website.json
- src/pages/home-page.module.scss
- src/pages/index.js
Fix:
- Responsiveness on homepage below 480px
- Home page video plays twice in some browsers
> chore(release): updating production to v1.0.7

- src/data/project-main-content/newrelic-newrelic-cli.mdx
Looks like an accidental repeat.
```bash
git push
```
- for functional corrections to code in the `src/components`, `src/templates`, …
> chore: Update newrelic-newrelic-cli.mdx

- src/pages/oss-category.js
Title change on the OSS Categories page for SEO
> chore: fixed title for oss categories

- src/data/projects/newrelic-video-agent-roku.json
file: newrelic-video-agent-roku.json
> fix: remove 'Browser' from 'description'

- src/data/project-main-content/newrelic-video-jwplayer-js.mdx
> Update repo URL.

- src/data/projects/open-telemetry.json
- src/pages/__tests__/fixtures/external-projects.js
- src/templates/__tests__/fixtures/external-project-page.js
Hi, I'm not sure if this is how you'd like to see this pull request but I made changes to typos in my name and GitHub user.
> chore: Update personal details

- README.md
- src/data/project-main-content/newrelic-infrastructure-agent.mdx
- src/data/project-stats/newrelic-aws-log-ingestion.json
- src/data/project-stats/newrelic-cloudformation-partner-integration.json
- src/data/project-stats/newrelic-developer-toolkit.json
- src/data/project-stats/newrelic-elixir_agent.json
- src/data/project-stats/newrelic-experimental-nr1-igor.json
- src/data/project-stats/newrelic-helm-charts.json
- src/data/project-stats/newrelic-infrastructure-agent.json
- src/data/project-stats/newrelic-newrelic-cli.json
- src/data/project-stats/newrelic-newrelic-client-go.json
- src/data/project-stats/newrelic-newrelic-jfr-mappers.json
- src/data/project-stats/newrelic-newrelic-python-agent.json
- src/data/project-stats/newrelic-newrelic-telemetry-sdk-dotnet.json
- src/data/project-stats/newrelic-newrelic-telemetry-sdk-node.json
- src/data/project-stats/newrelic-node-newrelic-koa.json
- src/data/project-stats/newrelic-node-newrelic.json
- src/data/project-stats/newrelic-nr1-apdex-optimizer.json
- src/data/project-stats/newrelic-nr1-workload-geoops.json
- src/data/project-stats/newrelic-nri-vsphere.json
- src/data/project-stats/newrelic-nri-zookeeper.json
- src/data/project-stats/newrelic-nrjmx.json
- src/data/project-stats/newrelic-opensource-website.json
- src/data/project-stats/newrelic-opentelemetry-exporter-java.json
- src/data/project-stats/newrelic-terraform-provider-newrelic.json
- src/data/projects/newrelic-infrastructure-agent.json
- src/data/projects/open-telemetry.json
- src/pages/__tests__/fixtures/external-projects.js
- src/templates/__tests__/fixtures/external-project-page.js
* chore: Update personal details (#496)
* chore: updated snaphsots (#495)
> chore(release): update open-telemetry details (no new site features) [v1.0.18]

- src/components/DarkModeToggle.js
- src/components/GlobalHeader.js
- src/components/GlobalHeader.module.scss
- src/components/Header.js
- src/components/Header.module.scss
- src/components/layout.js
Attempting to unify our selection of icons across the dev and open source site.
> fix(icon consistency): update global header icons (#7)

- src/data/project-main-content/open-telemetry.mdx
Video is going live on Tuesday. Merge then
```bash
git push
```
- for functional corrections to code in the `src/components`, `src/templates`, …
> Chore: Added video

- src/data/project-main-content/newrelic-terraform-provider-newrelic.mdx
- src/data/project-tags/project-tags.json
- src/data/projects/newrelic-terraform-provider-newrelic.json
Resolves: [developer-toolkit #27](https://github.com/newrelic/developer-toolkit/issues/27)
```bash
git push
```
- for functional corrections to …
> chore(projects): add newrelic/terraform-provider-newrelic to opensource projects

- src/data/project-main-content/newrelic-aws_s3_log_ingestion_lambda.mdx
- src/data/projects/newrelic-aws_s3_log_ingestion_lambda.json
> open source setup for aws s3 log ingestion

- src/components/styles.scss
I updated the images to have a max-width of 100% to ensure they shrink in in the viewport.
> fix: add responsive styling to images #505

- src/data/project-main-content/newrelic-newrelic-ruby-agent.mdx
- src/data/projects/newrelic-newrelic-ruby-agent.json
- src/data/projects/newrelic-ruby-agent.json
adds the .json  and .mdx files for the New Relic Ruby agent.
> chore(newrelic-ruby-agent): add New Relic Ruby agent project data files.

- src/data/project-main-content/newrelic-go-agent.mdx
- src/data/projects/newrelic-go-agent.json
This PR adds/updates the necessary two metadata files to add the Go Agent to the website.
> chore: Add the Go Agent to the list of projects

- src/data/project-main-content/newrelic-nri-ecs.mdx
- src/data/project-main-content/newrelic-nri-kube-events.mdx
- src/data/project-main-content/newrelic-nri-kubernetes.mdx
- src/data/projects/newrelic-nri-ecs.json
- src/data/projects/newrelic-nri-kube-events.json
- src/data/projects/newrelic-nri-kubernetes.json
- nri-ecs: https://github.com/newrelic/nri-ecs
- nri-kube-events: https://github.com/newrelic/nri-kube-events
- nri-kubernetes: https://github.com/newrelic/nri-kubernetes
```bash
git commit -m …
```
> chore: add Kubernetes & Containers integrations

- src/data/projects/newrelic-nri-kubernetes.json
We've just changed to main in this repo. It was the only one from the 3 we indexed in the previous PR that was using master.
```bash
git push
``` …
> chore(nri-kubernetes): change from master to main

- src/pages/nerdpacks.js
This linked lead to 404 page on the developer site, so I fixed it.
> fixed broken link to devsite

- src/data/project-main-content/newrelic-lambda-tracer-java.mdx
- src/data/projects/newrelic-lambda-tracer-java.json
add files for newrelic-lambda-tracer-java repo
> chore: add files for newrelic-lambda-tracer-java

- src/data/projects/newrelic-dropwizard-metrics-newrelic.json
- src/data/projects/newrelic-java-agent-api.json
- src/data/projects/newrelic-java-aws-lambda.json
- src/data/projects/newrelic-java-log-extensions.json
- src/data/projects/newrelic-micrometer-registry-newrelic.json
- src/data/projects/newrelic-newrelic-telemetry-sdk-java.json
- src/data/projects/newrelic-newrelic-tracer-java.json
Some updates to existing projects owned by Java agent team
> chore: Update existing projects owned by Java agent team

- src/components/seo.js
Add the title and info meta tags to the current page so Swiftype can index them
> Add Swiftype title and info meta tags

- package-lock.json
- package.json
- src/components/Header.js
- src/components/__tests__/__snapshots__/Header.spec.js.snap
- src/pages/__tests__/__snapshots__/collection.spec.js.snap
- src/pages/__tests__/__snapshots__/external-projects.spec.js.snap
- src/pages/__tests__/__snapshots__/index.spec.js.snap
- src/pages/__tests__/__snapshots__/oss-category.spec.js.snap
- src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
Closes https://github.com/newrelic/developer-website/issues/520
Enables global search in the OSS site
> chore: enable search

- .gitignore
- src/data/project-main-content/newrelic-experimental-nr-account-migration.mdx
- src/data/projects/newrelic-experimental-nr-account-migration.json
Added nr-account-migration metadata(JSON and MDX)
> feat(opensource-website) : Added nr-account-migration data

- src/data/project-stats/newrelic-demo-nodetron.json
- src/data/project-stats/newrelic-gatsby-plugin-newrelic.json
- src/data/project-stats/newrelic-gatsby-theme-newrelic.json
- src/data/project-stats/newrelic-go-agent.json
- src/data/project-stats/newrelic-newrelic-cli.json
- src/data/project-stats/newrelic-newrelic-java-agent.json
- src/data/project-stats/newrelic-newrelic-lambda-cli.json
- src/data/project-stats/newrelic-newrelic-lambda-layers.json
- src/data/project-stats/newrelic-newrelic-lambda-tracer-java.json
- src/data/project-stats/newrelic-node-newrelic-aws-sdk.json
- src/data/project-stats/newrelic-node-newrelic.json
- src/data/project-stats/newrelic-nr1-csg-cloud-journey.json
- src/data/project-stats/newrelic-terraform-provider-newrelic.json
> chore(stats): updated project stats files

- src/data/project-main-content/newrelic-infra-identity-client-go.mdx
- src/data/projects/newrelic-infra-identity-client-go.json
> chore: add newrelic/infra-identity-client-go

- src/pages/nerdpacks.js
Update video to https://www.youtube.com/watch?v=7omo0qHxku8&feature=youtu.be
```bash
git push
```
- for functional corrections to code in the …
> chore: Update nerdpacks.js

- src/data/project-main-content/newrelic-experimental-NewRelicReactNativeModule.mdx
- src/data/projects/newrelic-experimental-NewRelicReactNativeModule.json
> chore: Add New Relic React Native Module

- src/data/project-main-content/newrelic-newrelic-php-agent.mdx
- src/data/projects/newrelic-php-agent.json
Add the [PHP Agent](https://github.com/newrelic/newrelic-php-agent)
> chore: Add php agent

- src/components/seo.js
> chore: cleanup

- src/data/projects/newrelic-aws_s3_log_ingestion_lambda.json
- src/data/projects/newrelic-dropwizard-metrics-newrelic.json
- src/data/projects/newrelic-helm-charts.json
- src/data/projects/newrelic-java-aws-lambda.json
- src/data/projects/newrelic-lambda-tracer-java.json
- src/data/projects/newrelic-logstash-output-plugin.json
- src/data/projects/newrelic-micrometer-registry-newrelic.json
- src/data/projects/newrelic-module-util-java.json
- src/data/projects/newrelic-newrelic-airflow-plugin.json
- src/data/projects/newrelic-newrelic-fluent-bit-output.json
- src/data/projects/newrelic-newrelic-fluentd-output.json
- src/data/projects/newrelic-newrelic-java-agent-ansible-role.json
- src/data/projects/newrelic-newrelic-lambda-cli.json
- src/data/projects/newrelic-newrelic-lambda-layers.json
- src/data/projects/newrelic-newrelic-opencensus-exporter-go.json
- src/data/projects/newrelic-newrelic-opencensus-exporter-python.json
- src/data/projects/newrelic-opentelemetry-exporter-go.json
- src/data/projects/newrelic-opentelemetry-exporter-java.json
- src/data/projects/newrelic-python-agent-extension.json
> chore: changed category to community-plus for multiple projects

- .github/stale.yml
This PR adds the stalebot config to the repo.
> chore: added stalebot config

- src/data/projects/newrelic-newrelic-ruby-agent.json
Changed the "slug" value the newrelic-newrelic-ruby-agent.json file to match its corresponding .mdx.
> chore: Changed the slug value to match corresponding .mdx

- gatsby-config.js
Updates the NR Browser agent to be under a different account. This will require an update to alert policies and dashboards.
> Update NR Browser account

- src/data/projects/newrelic-experimental-nerd-vlog-demo-visualization.json
- src/data/projects/newrelic-experimental-nr1-funnelz.json
Updates two new project files to use same tag as specified in json file
> Fix to update project tags to match json file

- src/data/projects/newrelic-experimental-nr1-nrql-status-widget.json
Add NRQL Status Widget (custom dashboard viz) to projects.
cc/ @caylahamann
> chore: add nrql status widget project (custom viz)

- package.json
- yarn.lock
This PR bumps the theme which removes UTM params from the sign up button clicks, which should resolve some analytics problems.
> chore: bumps theme 

- src/components/Header.module.scss
Added a `top` to align the header on screens <480px with screens <724px
```bash
git push
```
- for functional corrections to code in the …
> fix: update header for mobile screens

- src/data/project-main-content/newrelic-newrelic-browser-agent.mdx
- src/data/projects/newrelic-newrelic-browser-agent.json
Adding the Browser Agent repo
https://github.com/newrelic/newrelic-browser-age
> chore: added browser agent

- gatsby-config.js
- package.json
- src/components/__tests__/__snapshots__/Header.spec.js.snap
- src/pages/__tests__/__snapshots__/collection.spec.js.snap
- src/pages/__tests__/__snapshots__/external-projects.spec.js.snap
- src/pages/__tests__/__snapshots__/index.spec.js.snap
- src/pages/__tests__/__snapshots__/oss-category.spec.js.snap
- src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
- yarn.lock
To enable splits, AKA A/B testing, a new button component has been added to the theme's header. This PR updates to that version of the theme and sets up the required configuration values.
Closes newrelic/gatsby-theme-newrelic/issues/356
> feat: Update theme to include A/B testing button

- .github/workflows/project-stats.yml
Alec here, back again with another YAML syntax fix
> fix: properly fix workflow syntax

- package.json
- yarn.lock
Fixes an issue in the global search
> Bump theme to 2.2.3

- gatsby-config.js
Adding Gatsby FF's that are used in Docs site to align build processes
> feat: adding feature flags to improve build times

- package.json
- src/components/__tests__/Header.spec.js
- src/components/__tests__/__snapshots__/Header.spec.js.snap
- src/pages/__tests__/__snapshots__/collection.spec.js.snap
- src/pages/__tests__/__snapshots__/external-projects.spec.js.snap
- src/pages/__tests__/__snapshots__/index.spec.js.snap
- src/pages/__tests__/__snapshots__/oss-category.spec.js.snap
- src/pages/__tests__/collection.spec.js
- src/pages/__tests__/external-projects.spec.js
- src/pages/__tests__/index.spec.js
- src/pages/__tests__/oss-category.spec.js
- src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
- src/templates/__tests__/external-project-page.spec.js
- yarn.lock
Bumps theme to latest version to bring in the new search XP, image links in new tab, and sending tessen events on feedback clicks
https://github.com/newrelic/gatsby-theme-newrelic/pull/375
> Bump theme

- .github/workflows/project-stats.yml
* remove commiting to develop from the workflow.
* also remove disabling, enabling branch protection since main is not
protected.
Resolves: #797
> chore: update project-stats workflow to commit to main only

- src/data/project-main-content/newrelic-tracker-google-publisher-tags-js.mdx
- src/data/projects/newrelic-tracker-google-publisher-tags-js.json
> chore: Add metadata files for GPT tracker

- package.json
- src/components/__tests__/__snapshots__/ProjectSearchInput.spec.js.snap
- yarn.lock
https://github.com/newrelic/gatsby-theme-newrelic/compare/v2.4.5...v2.5.0
> Bump theme to v2.5

- gatsby-config.js
Per Zoe and Austin, allow full url paths in referrer
> Change referrer policy to allow full url paths

- .github/stale.yml
> chore: relaxing state bot

- gatsby-config.js
- src/components/layout.js
- src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
OneTrust changes aren't ready yet, so reverting changes for now.
> chore: revert onetrust changes

- src/pages/home-page.module.scss
- src/pages/index.js
This PR remove the joel video and all css used for that video module.
> fix: remove joel

- src/pages/__tests__/__snapshots__/index.spec.js.snap
I ran: `yarn test -u`
```
snapshot Summary
› 1 snapshot updated from 1 test suite.
Test Suites: 8 passed, 8 total
Tests:       13 passed, 13 total
Snapshots:   1 updated, 9 passed, 10 total
Time:        21.713 s
Ran all test suites.
```
this PR updates the snap file as a test was failing on our last release.
> chore: updates  snapshots

- gatsby-config.js
fixes eslint errors in gatsby config.
> chore: eslint fixes

- gatsby-config.js
- package.json
- yarn.lock
This PR adds configuration to run  gatsby-build-newrelic on the OSS Site
> feat: added gatsby-build-newrelic

- .github/workflows/release.yml
Small update to fix an API call to the Github Branch protection API
> Fix branch protection API call

- src/data/project-main-content/newrelic-experimental-nr-pixie-security-plugin.mdx
- src/data/project-tags/project-tags.json
- src/data/projects/newrelic-experimental-nr-pixie-security-plugin.json
Add [New Relic Security Plugin for Pixie](https://github.com/newrelic-experimental/nr-pixie-security-plugin) repo and new security tag.
> chore: add security plugin project

- src/data/projects/open-telemetry.json
Updated the list of Relics participating in OpenTelemetry
```bash
git push
```
- for functional corrections to code in the `src/components`, …
> chore: update open-telemetry.json

- src/data/projects/open-telemetry.json
`chore` - made changes to content in `src/data/projects` directory
> Chore: Updated OTel contributors JSON file

- src/data/projects/newrelic-terraform-provider-newrelic.json
Small fix to update the Terraform support status
> fix: updated terraform to community plus
