- src/components/__tests__/__snapshots__/Header.spec.js.snap
- src/pages/__tests__/__snapshots__/collection.spec.js.snap
- src/pages/__tests__/__snapshots__/external-projects.spec.js.snap
- src/pages/__tests__/__snapshots__/index.spec.js.snap
- src/pages/__tests__/__snapshots__/oss-category.spec.js.snap
- src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
- src/templates/external-project-page.js
Fix
When a website url is available in the config file, use this link for the `View Website` button.
> fix: use website url for ext-projects when available

- src/components/styles.scss
Encode the semi colons in the css import of the open sans font from google fonts.
> Fix: the css mime type error 

- src/components/seo.js
The swiftype type field identifies the source website of each record in the swiftype search index. We use that to filter search results to specific websites. Once this is live we can point swiftype at opensource site to index all pages.
> feat(seo): Add meta tag for swiftype type field for all pages

- .github/ISSUE_TEMPLATE/bug_report.md
Super minor but noticed another non-US English spelling of 'behavior' crept in. I believe we are standardizing on US English for better or worse, so figured I'd throw a quick PR in.
> fix: standardize bug template 'behavior' spelling to US English.

- src/data/project-main-content/adopt-open-jdk.mdx
Fixes silver sponsor link from AdoptOpenJDK page
https://opensource.newrelic.com/projects/adopt-open-jdk
> chore: remove extra https://

- src/data/projects/newrelic-node-newrelic-koa.json
* Restores the previous project file, now that the repo has the appropriate licensing, etc.
* Adds default branch.
> chore: adds node-newrelic-koa back as community project.

- src/data/projects/newrelic-node-newrelic-superagent.json
- Restores the previous project file, now that the repo has the appropriate licensing, etc.
- Adds default branch.
> chore: adds node-newrelic-superagent project back as community project.

- src/pages/code-of-conduct-reporting.mdx
style: Updated "Code of Conduct" capitalization in the first sentence of the reporting guide.
> style: Updated CoC capitalization

- src/data/projects/newrelic-node-test-utilities.json
- Restores the previous project file, now that the repo has the appropriate licensing, etc.
- Adds default branch.
> chore: adds node-test-utilities project back as community project.

- src/data/projects/newrelic-node-newrelic-aws-sdk.json
* Restores the previous project file, now that the repo has the appropriate licensing, etc.
* Adds default branch.
> chore: adds node-newrelic-aws-sdk back as community project.

- src/data/projects/newrelic-node-native-metrics.json
* Restores the previous project file, now that the repo has the appropriate licensing, etc.
* Adds defaultBranch
> chore: adds newrelic-node-native-metrics back as a community project.

- src/components/Header.module.scss
Addresses: https://github.com/newrelic/opensource-website/issues/596
Noticed the mobile nav toggle button wasn't switching between the hamburger and close icons on the live site.
Looks like the rule currently on line 261 in `src/components/Header.module.scss` will never get applied since the `&` on the right would build to the `CSS` below, which won't match any elements since `.dark-mode` is applied at the base of the DOM tree on `body`:
```css
div.mobile-menu-active :global(.dark-mode) .mobile-menu-button {
background-image: url("../images/icon-menu-close-light.svg");
}
```
This commit combines two sets of style rules that should apply when the `mobile-menu-active` class is toggled on. I think this makes the rules a bit clearer, and it fixes the live bug.
> fix: ensure dark mode mobile button shows close icon

- src/data/projects/newrelic-node-newrelic-mysql.json
- Restores the previous project file, now that the repo has the appropriate licensing, etc.
- Adds defaultBranch
> chore: Restore node-newrelic-mysql back as a experimental project.

- src/data/project-main-content/newrelic-nr1-vscode-extension.mdx
- src/data/projects/newrelic-nr1-vscode-extension.json
This PR adds a project entry for the NR1 VSCode Extension
> Add nr1 vscode extension to projects

- src/data/project-main-content/newrelic-repolinter-action.mdx
- src/data/projects/newrelic-repolinter-action.json
- src/data/projects/newrelic-wiki-sync-action.json
This PR contributes project data for [Repolinter Action](https://github.com/newrelic/repolinter-action) and fixes a typo in Wiki Sync action's project data.
> chore: Add repolinter-action project data

- __mocks__/react-dom.js
- package-lock.json
- package.json
- src/components/CookieApprovalDialog.module.scss
- src/components/Footer.module.scss
- src/components/Header.js
- src/components/Header.module.scss
- src/components/HomePageHighlights.module.scss
- src/components/HomepageCollection.module.scss
- src/components/ProjectModule.module.scss
- src/components/ProjectSearchInput.module.scss
- src/components/__tests__/__snapshots__/Header.spec.js.snap
- src/components/nord-prism-theme.css
- src/pages/__tests__/__snapshots__/collection.spec.js.snap
- src/pages/__tests__/__snapshots__/external-projects.spec.js.snap
- src/pages/__tests__/__snapshots__/index.spec.js.snap
- src/pages/__tests__/__snapshots__/oss-category.spec.js.snap
- src/pages/collection.module.scss
- src/pages/home-page.module.scss
- src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
- src/templates/project-page.module.scss
These changes should address: https://github.com/newrelic/opensource-website/issues/556
The global nav should now mirror the experience on https://developer.newrelic.com/ as requested in the bug ticket.
I can see the global Gatsby theme nav was disabled on mobile views and set to be `static` rather than `sticky`. I caught and resolved a couple complications from removing the mobile `display: none` rule, but it's worth some manual exploration to confirm there aren't regressions I didn't clock.
1.  My changes in 16f614f modify some styles that link back to changes in https://github.com/newrelic/opensource-website/commit/637f7e09d307757a2ea3fe35e0cac1e5642fc203, which I'm not familiar with. Might be worth someone close to that work giving this MR's changes a glance
2. I added a `z-index` for …
> fix: add Gatsby theme New Relic global nav to Open Source site mobile views (#556)

- src/components/Header.module.scss
Ensure the header backdrop expands to the full browser viewport.
**Before**
**After**
> Ensure header has backdrop that goes the full browser viewport

- src/data/projects/newrelic-node-native-metrics.json
This PR upgrades newrelic-node-native-metrics to the community-plus category.
> chore: upgreade newrelic-node-native-metrics to community-plus

- .github/workflows/pr.yml
Fixes an issue I noticed with the Project Tags check from PR #628 (when file is deleted the workflow check blew up).
> fix: add check to see if file exists before require

- src/data/projects/newrelic-node-newrelic-mysql.json
This PR reverts the `newrelic/node-newrelic-mysql` package back to `new-relic-experimental`.  The `community-plus` categorization was incorrect and related to the existence of the "in agent" MySQL instrumentation.  We regret the error.
> chore: Reverting newrelic/node-newrelic-mysql to Experimental

- src/data/project-main-content/newrelic-newrelic-jfr-reporter.mdx
- src/data/projects/newrelic-newrelic-jfr-reporter.json
Adds newly open sourced repo: https://github.com/newrelic/newrelic-jfr-reporter
> chore: Add newrelic-jfr-reporter repo to OSS site

- .github/workflows/pr.yml
- src/data/projects/newrelic-experimental-quickstarts.json
adds the quickstarts project to the OSS Site
set env to new GH format based on this article: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> chore: added Quickstarts project

- .github/workflows/pr.yml
@jpvajda This is an additional fix for the set-env fix you applied earlier. I borrowed this same code for some work we're doing in the open-install-library. For this: 
`PROJECT_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep "src/data/projects" || true)`
If multiple lines match that grep statement, the env-var needs to be set like I've included in this PR. 
open-install-library ref: https://github.com/newrelic/open-install-library/commit/4081ea23aad0c9adfed204ca6232c8f09d4f928d#diff-252ba10f2c12f181d79ca1f94e44360061f4a28a8b52c7a7f0bc3f152f2564be
> fix: support multi-line env var

- src/data/project-tags/project-tags.json
- src/data/projects/newrelic-experimental-newrelic-kafka-playground.json
- src/data/projects/newrelic-infra-identity-client-go.json
- src/data/projects/newrelic-nr1-cloud-optimize.json
- src/data/projects/newrelic-nri-ecs.json
- src/data/projects/newrelic-nri-kube-events.json
- src/data/projects/newrelic-nri-kubernetes.json
- src/data/projects/newrelic-terraform-newrelic-apm.json
This PR removes the infrastructure tag and replaces each of those projects with the nri (New Relic Infrastructure) tag for consistency with how we tag these projects. 
Issue: https://github.com/newrelic/opensource-website/issues/459
> chore: updated infra tags

- src/data/project-tags/project-tags.json
- src/data/projects/newrelic-experimental-nerd-vlog-demo-visualization.json
- src/data/projects/newrelic-experimental-nr1-funnelz.json
Adds a visualization project tag! We're trying to get visualizations their own project tag on the opensource website and begin to add more repos that hopefully users can refer to when building their own visualizations! 
Additionally this adds two visualization repos to the opensource website: 
* nr1-funnelz 
* Nerd Log Demo Visualization
> Add visualization project tag and visualization repos

- package.json
- yarn.lock
This PR removes the old gdpr package we used for cookie consent as we now have that built into our theme.
> chore: removed old gdpr package

- .github/workflows/pr.yml
- .github/workflows/project-stats.yml
- .github/workflows/release.yml
- .releaserc
This PR fixes some settings in the yml files that were still pointing to the package-lock.json file and also corrects the path to be yarn.lock.
> chore: missing yarn configurations

- gatsby-config.js
This PR sets the segment write key to the correct one for the opensource.newrelic.com source in Segment.
> chore: updated segment write key

- .github/workflows/release.yml
Some of the workflows were still specifying node 10, this updates them all to node 12.
> fix: update node version in workflows

- .github/workflows/pr.yml
- .github/workflows/project-stats.yml
- CONTRIBUTING.md
- amplify.yml
- docs/Architecture.md
- docs/Build-and-Deploy.md
- docs/Emergency-Runbook.md
- docs/Open-Source-Category-Snippets.md
- docs/Project-Structure.md
- src/templates/project-page.js
Cycled through every reference to the `master` branch and changed them to `main`. Includes several docs pages and workflows to align with the changes already made to Amplify
> chore: Changing all relevant references of master to main branch

- package.json
- yarn.lock
Updates to 2.2.2 which includes a reduction in console warnings and whitespace wrapping in codeblocks
> Update gatsby theme

- package.json
- src/components/__tests__/fixtures/ProjectSearchInput.js
- src/pages/__tests__/fixtures/explore-projects.js
- src/pages/__tests__/fixtures/external-projects.js
- src/pages/cla.mdx
- src/pages/code-of-conduct-reporting.mdx
- src/pages/code-of-conduct.mdx
- src/pages/collections.js
- src/pages/contributing.mdx
- src/pages/explore-projects.js
- src/pages/external-projects.js
- src/pages/index.js
- src/pages/instrumentation.js
- src/pages/layouts.js
- src/pages/nerdpacks.js
- src/templates/external-project-page.js
- src/templates/project-page.js
- yarn.lock
It seems `componentPath` is no longer available on allSitePage in v3.5 so I replaced it with `component` which appears to be an identical value
Closes https://github.com/newrelic/opensource-website/issues/776
> Bump gatsby to 3.5

- src/data/project-main-content/newrelic-nr1-victory-visualizations.mdx
- src/data/projects/newrelic-nr1-victory-visualizations.json
Adds the [nr1-victory-visualizations](https://github.com/newrelic/nr1-victory-visualizations) project to the OSS site
> Add nr1-victory-visualizations listing

- package.json
- yarn.lock
Updates the theme to a version that handles blocked cookies. Unfortunately, this site also has some components that break when access to browser APIs is blocked. ~~I am writing up an issue for that.~~ That issue is here: https://github.com/newrelic/opensource-website/issues/795
Closes https://github.com/newrelic/docs-website/issues/2293
> fix: bump theme to version that handles blocked cookies

- package.json
- src/components/ProjectSearchInput.js
- src/components/__tests__/__snapshots__/ProjectSearchInput.spec.js.snap
- yarn.lock
This PR upgrades Gatsby to v3.8 and refactors the drop down selectors to use our theme components
Closes https://github.com/newrelic/opensource-website/issues/803
> Gatsby v3.8 and drop down refactor

- src/data/project-main-content/newrelic-tracker-prebid-js.mdx
- src/data/projects/newrelic-tracker-prebid-js.json
Add prebid tracker metadata. As an FYI, the project page may not load for people with adblockers installed, but there's no real way around that without renaming the project beyond reason.
> chore: Add Prebid Tracker json and metadata

- src/data/project-main-content/newrelic-video-caf-js.mdx
- src/data/projects/newrelic-video-caf-js.json
@jpvajda Adding some metadata for an existing open source project, our chromecast tracker. Had to open close duplicate PR as the last one had a check that was hanging.
> chore: add CAF project metadata

- gatsby-config.js
- package.json
- yarn.lock
Adds config option for gatsby cloud plugin to change referrer-policy from `same-origin` to `strict-origin`.
Partially addresses https://github.com/newrelic/gatsby-theme-newrelic/issues/437
> Change referrer policy to expose referrer for external link clicks

- gatsby/create-pages.js
- src/data/projects/newrelic-newrelic-quickstarts.json
This adds logic for redirects within project pages and adds the specific redirect of `/projects/newrelic/nr1-quickstarts` to `/projects/newrelic/newrelic-quickstarts`
Closes https://github.com/newrelic/opensource-website/issues/850
To review:
Both `/projects/newrelic/nr1-quickstarts/` and `/projects/newrelic/nr1-quickstarts` (with and without trailing slash) should redirect to `/projects/newrelic/newrelic-quickstarts`
> Add redirect logic for projects with local redirects

- .github/workflows/release.yml
This disables/enables Branch protection on the release workflow, using [Octokit](https://octokit.github.io/rest.js/v18)
> fix: enable/disable branch protection

- src/data/project-main-content/newrelic-newrelic-pino-logenricher-node.mdx
- src/data/projects/newrelic-newrelic-pino-logenricher-node.json
- src/data/projects/newrelic-newrelic-winston-logenricher-node.json
I added a new entry for Pino Log Enricher.  I also updated links to point to the correct monorepo for Winston Log Enricher.  I had a few questions:
* The pino page lacks repo stats and top contributors, how does this get built and does it not work locally?
* The top contributors for winston differ locally than they do in production
* The naming convention suggested for files will not work in a monorepo so I used my best judgement, will this be ok?
> chore: added pino log enricher, updated urls for winston log enricher as they moved to monorepo

- src/data/projects/newrelic-node-newrelic-aws-sdk.json
- src/data/projects/newrelic-node-newrelic-koa.json
- src/data/projects/newrelic-node-newrelic-superagent.json
- src/data/projects/newrelic-node-newrelic.json
- src/data/projects/newrelic-node-test-utilities.json
This fixes an issue where `supportUrl` for most Node.js agent team modules was wrong.
> fix: updated support link for all Node.js agent modules

- src/data/project-main-content/newrelic-newrelic-node-nextjs.mdx
- src/data/projects/newrelic-newrelic-node-nextjs.json
I added a new entry for `@newrelic/next` instrumentation.  This repo is still private and plan on making public early next week.  I just wanted to get this PR in now as it's one of the last items of our MMF.  Closes https://github.com/newrelic/newrelic-node-nextjs/issues/10
> chore: added next.js instrumentation module

- .github/CODEOWNERS
- .github/workflows/release.yml
- docs/Emergency-Runbook.md
- Created new [Docs Engineering Team](https://github.com/orgs/newrelic/teams/docs-engineering/)
- Added team as Admin to [OSS](https://github.com/newrelic/opensource-website)
- Added `CODEOWNERS` file
- Remove references to `Developer Enablement` and updated to `Docs Engineering`
Resolves https://github.com/newrelic/docs-website/issues/6562
> Codeowners for OSS

- src/data/projects/newrelic-nrjmx.json
Update support tier to Community Plus, based on current readme at https://github.com/newrelic/nrjmx#readme
> chore: update nrjmx support tier
